### ISSUE TITLE
MultiLocs make troubles

### ISSUE THREAD

**Issue by mikawa** [EricEve/adv3lite#18]
I found out that Multilocs show up unwanted behaviour:
If a MultiLocs inherits from Fixture, the error won't show up.
If a Multilocs inherits from Distant or Decoration, trying to unlock a lockable Thing in the same location calls up their desc() funtion or notImportantMsg().
I think this happens during trying to find a suitable key for the lock.
Again, I don't have time to dig in deeper as I have to finish my WIP for IFcomp. I can do some debugging after comp release.

**Comment by EricEve** [comment]
This is happening during trying to find a suitable key for the lock, because the notImportantMsg on the Decoration in question (the clouds) was defined as a double-quoted string instead of a single-quoted string (as it should have been), so this turns out to be a user error, not a library bug.
